Added man pages for fence types
concurrencykit/ck pull request #239
Opened 2024-11-20 17:37 UTC by LucaJetB

Added man pages for fence types

`ck_pr_fence_lock()`
`ck_pr_fence_unlock()`
`ck_pr_fence_acqrel()`

Resolves #202

2024-11-23 05:53 UTC, sbahra requested changes

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +.Nd enforce ordering of acquire and release operations
See https://preshing.com/20130922/acquire-and-release-fences/ and https://sabrinajewson.org/rust-nomicon/atomics/fences.html for more documentation. I would propose a better description along those lines.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +invocations of an acquire and a release fence, normally called by two different threads, allowing for code simplicity.
The fences are not necessarily called on two different threads. Let's just describe the ordering guarantees of the fence here and not delve into intention or similar, for accuracy purposes. On some architectures, there are performance reasons to use acqrel.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +This function enforces the ordering of any memory aquire and release operations
The ordering is enforced on loads, stores and other operations in memory (I would just refer to ck_pr operations). Note, typo in "aquire" as well.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +relative to the invocation of the function on both the subsequent and preceeding ends. This function effectively combines the
Let's use same line width, try to keep number of columns 80 lines or less for convenient viewing in a terminal.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +.Sh EXAMPLE
Let's ditch the example entirely.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_acqrel
> +.Xr ck_pr_stall 3 ,
Let's only refer to ck_pr_fence operations in SEE ALSO.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_lock
> +Any realted operations that were performed prior to the invocation of
Typo here, but we discussed it in person. This is really just an optimization as in some architectures the atomic operations themselves in force some amount of ordering of memory operations and we may only need to insert a control dependency.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_lock
> +.Sh SEE ALSO
Same comment as above, let's refer to ck_pr_fence functions only here.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_unlock
> +Any realted operations (or operations in the critical section) that were performed prior to the invocation of
Typo and same comments as above.

2024-11-23 05:53 UTC, sbahra commented on doc/ck_pr_fence_unlock
> +.Sh EXAMPLE
Let's ditch examples.

2024-11-24 23:08 UTC, LucaJetB reviewed
Updated based on comments

2024-12-07 02:10 UTC, sbahra requested changes
Just some minor changes requested, and we can put it in.

2024-12-07 02:10 UTC, sbahra commented on doc/ck_pr_fence_lock
> +This function serves as an optimization surrounding atomic lock operations.
Let's drop this sentence as the purpose is to enforce ordering, it is more optimal than other options, but that is still it's purpose.

2024-12-07 02:10 UTC, sbahra commented on doc/ck_pr_fence_lock
> +Atomic operations will enforce their own ordering and therefore
This may not be the case. Let's just change this sentence to "This function serves as an implicit compiler barrier."

2024-12-07 02:10 UTC, sbahra commented on doc/ck_pr_fence_unlock
> +This function serves as an optimization surrounding atomic unlock operations.
Same thing here, let's drop this sentence. Let's apply same spirit of changes as the corresponding lock fence.

2024-12-14 02:43 UTC, merged